services:
  mongo-dev:
    image: mongo:latest
    container_name: inventory_mongodb_dev
    ports:
      - "27019:27017"
    volumes:
      - mongo_data_dev:/data/db
    networks:
      - mern_network_dev
    restart: always

  backend-dev:
    image: ${DOCKER_USERNAME}/ims-backend:dev
    container_name: inventory_backend_dev
    ports:
      - "5002:5000"
    environment:
      - MONGO_URI=mongodb://mongo-dev:27017/inventory_dev
      - PORT=5000
    depends_on:
      - mongo-dev
    networks:
      - mern_network_dev
    restart: on-failure

  frontend-dev:
    image: ${DOCKER_USERNAME}/ims-frontend:dev
    build:
      context: ./Frontend/inventory_management_system
      dockerfile: Dockerfile
      args:
        BACKEND_HOST: backend-dev
    container_name: inventory_frontend_dev
    ports:
      - "3002:80"
    depends_on:
      - backend-dev
    networks:
      - mern_network_dev
    restart: on-failure

volumes:
  mongo_data_dev:

networks:
  mern_network_dev:
    driver: bridge
