services:
  mongo:
    image: mongo:latest
    container_name: inventory_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mern_network
    restart: always

  backend:
    image: ${DOCKER_USERNAME}/ims-backend:prod
    container_name: inventory_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/inventory_production
      - PORT=5000
    depends_on:
      - mongo
    networks:
      - mern_network
    restart: on-failure

  frontend:
    image: ${DOCKER_USERNAME}/ims-frontend:prod
    build:
      context: ./Frontend/inventory_management_system
      dockerfile: Dockerfile
      args:
        BACKEND_HOST: backend
    container_name: inventory_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - mern_network
    restart: on-failure

volumes:
  mongo_data:

networks:
  mern_network:
    driver: bridge
